kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-openshift-ingress
subjects:
- kind: ServiceAccount
  name: knative-openshift-ingress
roleRef:
  kind: Role
  name: knative-openshift-ingress
  apiGroup: rbac.authorization.k8s.io
